### PR TITLE
Fix rspec

### PR DESCRIPTION
**Pull request by yosoynatebrown**
### Project Management
Issue name:

Closes #

------------------------------------------------------------------------------
### Feature Status
* [x] Completed
* [ ] In progress

------------------------------------------------------------------------------
### Test coverage

* [ ] 100% Model Testing
* [ ] 100% Feature Testing

If below 100%, what still needs testing:
- x

------------------------------------------------------------------------------
### Change Log

What I did:
- x

Things to consider:
- x

What needs to be refactored:
- x

What still needs help:
- x

### CODE REVIEW

**Comment by bfrey08** [comment]
Looks like tests all pass if I use `bundle exec rspec` however if I need to update gems to use `rspec` and then 3 tests fail. I've isolated it to an issue with the update on `gem 'omniauth-google-oauth2'` I will look more into this today

**Comment by bfrey08** [comment]
It looks like circle CI still has 3 failing tests, undetermined if it is related to the above 3 failing tests.

**Comment by yosoynatebrown** [comment]
Yeah I got interrupted playing pickle ball with my mom. Should have dropped something in Slack about how I'm still working on trying to get Selenium to work on CircleCI. Ideally I'd like to get back to the green checkmark because the tests are passing locally on my machine. Just need to find the right setup in the config.yml file.

**Comment by bfrey08** [comment]
YAHOOOOO RSPEC TESTS AND CIRCLE CI IS PASSING AGAIN!

**Pull request merged**
